# Generated by Django 2.2.6 on 2019-10-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default='hola', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='comuna',
            field=models.CharField(default='hola', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(default='hola', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.CharField(default='hola', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='hola', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vivienda',
            field=models.CharField(default='hola', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='hola', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default='hola', max_length=50),
        ),
    ]
