# Generated by Django 2.2.6 on 2019-11-06 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistro', '0002_auto_20191017_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nacimiento',
            field=models.DateField(default=datetime.date(1997, 10, 19)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='no_asignado', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default='no_asignado', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='comuna',
            field=models.CharField(default='no_asignado', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='no_asignado', max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default='no_asignado', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='region',
            field=models.CharField(default='no_asignado', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='run',
            field=models.CharField(default='no_asignado', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='no_asignado', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='vivienda',
            field=models.CharField(default='no_asignado', max_length=50),
        ),
    ]
