# Generated by Django 2.2.7 on 2019-11-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(default='/media/placeholder.png', upload_to='autores/')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.ImageField(default='/media/placeholder.png', upload_to='editoriales/')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('portada', models.ImageField(default='/media/placeholder.png', upload_to='libros/')),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('isbn', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete='CASCADE', to='appEditorial.Autor')),
                ('editorial', models.ForeignKey(on_delete='CASCADE', to='appEditorial.Editorial')),
            ],
        ),
    ]
