# Generated by Django 2.2.7 on 2019-11-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEditorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('isbn', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete='CASCADE', to='appEditorial.Autor')),
                ('editorial', models.ForeignKey(on_delete='CASCADE', to='appEditorial.Editorial')),
            ],
        ),
    ]
