# Generated by Django 2.2.7 on 2019-11-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEditorial', '0002_autor_editorial_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(default='/static/img/triquetra.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='autor',
            name='foto',
            field=models.ImageField(default='/static/img/triquetra.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='logo',
            field=models.ImageField(default='/static/img/triquetra.png', upload_to=''),
        ),
    ]
